### ISSUE TITLE
feature request: should remove the draft release

### ISSUE THREAD

**Issue by jakoch** [nikhilbadyal/ghaction-rm-releases#242]
hey! 
i'm using your action and would like to request a feature: 
currently the action deletes a tag and the release will be put into draft mode.
could you add that the draft releases are deleted, too?

**Comment by nikhilbadyal** [comment]
That's how it work. Can you give some example where draft is being made when release is deleted.

**Comment by jakoch** [comment]
My repo using your action is: https://github.com/jakoch/reaper-toolbox
A new toolbox is created weekly, tagged and automatically released from Azure Pipelines to Github Releases.
I ran your action as a manual workflow and expected that it would delete all old releases, but it puts them into draft mode.
This is a screenshot of https://github.com/jakoch/reaper-toolbox/releases

![github com_jakoch_reaper-toolbox_releases](https://github.com/nikhilbadyal/ghaction-rm-releases/assets/85608/a3f30f0d-9952-4532-b343-7e794f550cee)

**Comment by nikhilbadyal** [comment]
Fixed in [new version](https://github.com/nikhilbadyal/ghaction-rm-releases/releases/tag/v0.0.3).
